enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
excluded-patches = "'Hide endscreen cards' 'Hide info cards' 'Disable rolling number animations' 'Hide seekbar' 'Hide timestamp' 'Wide searchbar' 'Spoof app version' 'Theme' 'Announcements' 'Always repeat' 'Enable debugging' 'Spoof device dimensions'"
