enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "both"
excluded-patches = "'Always repeat' 'Spoof device dimensions' 'Announcements' 'Enable debugging' 'Tablet mini player' 'Wide searchbar' 'Enable tablet layout' 'Hide cast button' 'Hide captions button' 'Hide autoplay button' 'Spoof app version' 'Change start page' 'Theme' 'Hide endscreen cards' 'Comments' 'Hide floating microphone button' 'Hide seekbar' 'Disable rolling number animations' 'Hide crowdfunding box' 'Hide info cards' 'Hide filter bar' 'Disable suggested video end screen' 'Player flyout menu' 'Hide album cards' 'Hide timestamp'"
